### ISSUE TITLE
Added VC14&OpenCV3.2 support 

### ISSUE THREAD

**Issue by DeadSix27** [max20091/waifu2x-converter-cpp#1]
Hey, I improved upon your changes.
If you want we can collaborate, reply here if you're up for that.
I can add you as contributor on my fork.
(I already committed some changes)

I also got rid of the extra no-cuda branch and merged both into master

See: https://github.com/DeadSix27/waifu2x-converter-cpp

**Comment by max20091** [comment]
Thanks, I will see it later.

**Comment by DeadSix27** [comment]
Oh and you probably can help me fix some compilation issues I run into:
7>w2xcr.obj : error LNK2019: unresolved external symbol __imp_w2xconv_convert_file referenced in function proc_thread
I had it compile fine before, completely out of ideas why it won't work now..
